'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LockKeyhole, ArrowRight, ShieldCheck, Crown } from 'lucide-react';
export function Entry({ onEnter, busy, error }: {
    onEnter: (pin: string) => void;
    busy: boolean;
    error: string;
}) { const [code, setCode] = useState(''); return <main className="entry"><header className="brand"><span className="brand-mark">♞</span> RIVAL ROOM <span className="private-badge"><LockKeyhole size={12}/> JUST YOU TWO</span></header><div className="entry-grid"><section><p className="eyebrow">YOUR PRIVATE CHESS CLUB</p><h1>Good friends.<br /><em>Great rivals.</em></h1><p className="intro">One board. Two players. A score that settles the debate.</p><form className="gate" onSubmit={e => { e.preventDefault(); onEnter(code); }}><div className="gate-title"><LockKeyhole size={18}/><h2>Take your seat.</h2></div><label htmlFor="code">Your personal access code</label><div className="code-row"><Input id="code" type="password" inputMode="numeric" placeholder="8-digit code" maxLength={8} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))}/><Button type="submit" disabled={busy || code.length !== 8}>{busy ? 'Opening…' : 'Enter room'} <ArrowRight size={16}/></Button></div>{error && <p className="error" role="alert">{error}</p>}<p className="muted">Your code is your seat. No accounts. No sign-up.</p></form><div className="entry-points"><span><ShieldCheck size={16}/> Private by invitation</span><span><Crown size={16}/> Every result counts</span></div></section><div className="board-poster"><div className="poster-top"><span>THE NEXT CHAPTER</span><b>YOU vs. THEM</b></div><div className="mini-board">{Array.from({ length: 64 }, (_, i) => <div key={i} className={(Math.floor(i / 8) + i % 8) % 2 ? 'dark' : 'light'}>{i < 16 ? ('♜♞♝♛♚♝♞♜♟♟♟♟♟♟♟♟'[i]) : i > 47 ? ('♙♙♙♙♙♙♙♙♖♘♗♕♔♗♘♖'[i - 48]) : ''}</div>)}</div><div className="poster-bottom"><span>1 / 3 / 5 / 10 MIN</span><span>BRAGGING RIGHTS INCLUDED ↗</span></div></div></div><footer>RIVAL ROOM <span>Small circle. Long-running rivalry.</span></footer></main>; }
